### PR TITLE
Add layout customization support

### PR DESCRIPTION
**Pull request by zekker6**
Thanks for this app! 
I wanted to have dark theme to use, so ended up implementing it :)

Here are a few examples of how it looks like:
- Your profile
  [Your profile](https://gh-stats.zekker-dev.tk/?username=zekker6&theme=dark)
- gamersforever1695 (a contributor here)
 [gamersforever1695](https://gh-stats.zekker-dev.tk/?username=zekker6&theme=dark)

### CODE REVIEW

**Comment by LordDashMe** [comment]
This is cool! 👍  let us review it further. 

Thanks @zekker6!

**Comment by LordDashMe** [comment]
Hi, @zekker6, I think we are near to do the all customizable thing. Can we make the following items to be more customizable via query params?

- background
  - fill
  - stroke
- title
- stats
- rating
- icons

So the URL will be something like:

```
?username=zekker6&backgroundFill=#000&...
```

**Comment by zekker6** [comment]
@LordDashMe Thanks for review, implemented this.

[test](https://gh-stats.zekker-dev.tk/?username=zekker6&theme=dark)


`backgroundFill: fff`
[test](https://gh-stats.zekker-dev.tk/?username=zekker6&theme=dark)

**Comment by zekker6** [comment]
@LordDashMe Just a reminder this one needs some review and probably merge if it looks good to you

**Comment by LordDashMe** [comment]
> @LordDashMe Just a reminder this one needs some review and probably merge if it looks good to you

Alright! LGTM, but let us review it further. Thanks @zekker6 👍

**Comment by MrBartusek** [comment]
@LordDashMe any update on this?

**Comment by LordDashMe** [comment]
> @LordDashMe any update on this?

Thanks for the interest with this feature PR, there are an ongoing reviews and plan to release this feature. So hold tight, it will be push to production soon. ☺️

**Pull request closed without merging**
